#!/Users/temporary/anaconda3/envs/VVCORE_dynasor/bin/python
import numpy as np
import time
import argparse

# Custom dependences
from VVCORElib_mpi import save_signal, stack
from VVCORElib_mpi import compute_signal

def parser():
    """Parser of the arguments"""
    parser = argparse.ArgumentParser(description='VVCORE - autocorrelation function tool')
    parser.add_argument('-path', type=str, default='./', help='Path to the folder with trajectory')
    parser.add_argument('-i', type=str, default='data.dat', help='Input file with MD trajectory')
    parser.add_argument('-opt', type=str, default='dens cur_T cur_L', help='Program option')
    parser.add_argument('-N_frames', type=int, default=10000, help='Number of frames readed in one chunk')

    parser.add_argument('-lattice', type=str, choices = ['fcc', 'bcc', 'sc', 'file'], default='fcc', help='Lattice of the crystal (for none qubic set qpoints explitely in qpoint.h5 file)')
    parser.add_argument('-Nq_path', type=int, default=50, help='Number of q points to resolve (for cubic lattices) along path')
    parser.add_argument('-Nq', type=int, default=150, help='Total number of q points to resolve (for cubic lattices)')
    parser.add_argument('-a', type=float, default=None, help='Lattice constant for cubic lattices')
    parser.add_argument('-c', type=float, default=None, help='Lattice constant for hexagonal lattices')
    parser.add_argument('-M', type=str, default=None, help='Masses of the species')
    
    parser.add_argument('--partial', help='Option for computing all partial contributions', action='store_true')
    
    parser.add_argument('--phase_noise', help='Option for adding noise to atomic vibrations (flips the velocity of random atoms)', action='store_true')
    parser.add_argument('-noise_ind', type=int, default=0, help='Specifies to what atoms noise should be added')
    parser.add_argument('-noise_ratio', type=float, default=0.0, help='Ratio of noisy atoms')
    args = parser.parse_args()
    return args

if __name__ == "__main__":
    
    start_time_program = time.time()
    from mpi4py import MPI
    comm = MPI.COMM_WORLD
    
    args = parser()

    path = args.path
    traj_file = f"{path}/{args.i}"
    opts = args.opt.split()

    N = args.N_frames

    lattice = args.lattice
    Nq_path = args.Nq_path
    Nq = args.Nq
    a = args.a
    c = args.c
    
    if not isinstance(args.M, type(None)):
        M = args.M.split()
        M = {str(i+1): np.float64(M[i]) for i in range(len(M))}
    
    partial = args.partial
    
    phase_noise = args.phase_noise
    noise_ind = args.noise_ind
    noise_ratio = args.noise_ratio
    
    if noise_ind >= len(M.keys()):
        raise ValueError('Index of atom is out of bounds')
    
    start_time_signal = time.time()
    #################  Compute signal part  #############################################3
    res, read_time, compute_time = compute_signal(traj_file, N, Nq_path, Nq, lattice, a, c, M, opts, partial, phase_noise, noise_ind, noise_ratio, comm)

    time_signal = time.time() - start_time_signal
    
    #################  Save signal part ################################
    start_time_comm_1 = time.time()
    
    for opt in opts:
        res_cur = comm.gather(res[opt], root = 0)

        if comm.rank == 0:
            res_cur = stack(res_cur)
            save_signal(res_cur, f"{path}/{opt}.h5")
            del res_cur
        res.pop(opt)


    comm.Barrier()
    
    time_comm_1 = time.time() - start_time_comm_1
    time_program = time.time() - start_time_program
    
